# Server config
server:
  servlet:
    context-path: /travel
  port: 9000

travel-api:
  baseUrl: http://localhost:8080
  oauth2:
    client:
      grantType: client_credentials
      clientId: travel-api-client
      clientSecret: psw
      accessTokenUri: http://localhost:8080/oauth/token
      scope: read
  endpoints:
    airports: /airports
    fares: /fares
